version: "2.1"
services:

  app:
    build: ./
    container_name: app
    ports:
      - "8011:8011"
    depends_on:
      - postgre
      - minio1
      - redis
    environment:
#      - SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      - "SPRING_PROFILES_ACTIVE=docker"

  postgre:
    image: postgres:11.7
    container_name: postgre
    environment:
      - POSTGRES_PASSWORD=58742
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storage
    ports:
      - "5432:5432"

  minio1:
    image: 'bitnami/minio:latest'
    container_name: minio1
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key

  redis:
    image: redis:6.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  data1-1:
  data1-2:
  redis-data: