version: "2"
services:

  web:
    build: ./
    container_name: web
    ports:
      - "8011:8011"
    depends_on:
      - db
#    environment:
#      - SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
#      - "SPRING_PROFILES_ACTIVE=dev"

  db:
    image: postgres:11.7
    container_name: db
    environment:
      - POSTGRES_PASSWORD=58742
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storage
    ports:
      - "5432:5432"