version: "2.1"
services:

  app:
    build: ./
    container_name: app
    ports:
      - "8011:8011"
    depends_on:
      - postgre
      - minio1
      - redis
    environment:
#      - SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      - "SPRING_PROFILES_ACTIVE=docker"

  postgre:
    image: postgres:11.7
    container_name: postgre
    environment:
      - POSTGRES_PASSWORD=58742
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storage
    ports:
      - "5432:5432"

  minio1:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:6.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  data1-1:
  data1-2:
  redis-data: