version: "2"
services:

  app:
    build: ./
    container_name: app
    ports:
      - "8011:8011"
    depends_on:
      - postgre
    environment:
#      - SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      - "SPRING_PROFILES_ACTIVE=docker"

  postgre:
    image: postgres:11.7
    container_name: postgre
    environment:
      - POSTGRES_PASSWORD=58742
      - POSTGRES_USER=postgres
      - POSTGRES_DB=storage
    ports:
      - "5432:5432"