server:
  port: 8011
  servlet:
    context-path: /storage

minio:
  url:  http://127.0.0.1:9000
  key:
    access: minioadmin
    secret: minioadmin

redis:
  host: redis://127.0.0.1
  port: 6379

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/storage
    username: postgres
    password: 58742